// Command genzones writes internal/almanac/zones_gen.go: the names in the
// Go toolchain's tz database (lib/time/zoneinfo.zip, the same data that
// time/tzdata embeds). Run it with `go generate ./...` after a Go upgrade;
// a test fails if the list and the toolchain disagree.
package main

import (
	"archive/zip"
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	out, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		fail(err)
	}
	root := strings.TrimSpace(string(out))
	zr, err := zip.OpenReader(filepath.Join(root, "lib", "time", "zoneinfo.zip"))
	if err != nil {
		fail(err)
	}
	defer zr.Close()
	var names []string
	for _, f := range zr.File {
		if !strings.HasSuffix(f.Name, "/") {
			names = append(names, f.Name)
		}
	}
	sort.Strings(names)
	version := "unknown"
	if b, err := os.ReadFile(filepath.Join(root, "lib", "time", "update.bash")); err == nil {
		for _, line := range strings.Split(string(b), "\n") {
			if v, ok := strings.CutPrefix(line, "DATA="); ok {
				version = strings.TrimSpace(v)
			}
		}
	}
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by cmd/genzones from the Go toolchain's lib/time/zoneinfo.zip; DO NOT EDIT.\n\npackage almanac\n\n")
	fmt.Fprintf(&buf, "// TZDataVersion is the IANA tz database release the list came from.\nconst TZDataVersion = %q\n\n", version)
	fmt.Fprintf(&buf, "// zoneNames lists every zone Go's tz database knows, sorted.\nvar zoneNames = []string{\n")
	for _, n := range names {
		fmt.Fprintf(&buf, "\t%q,\n", n)
	}
	buf.WriteString("}\n")
	src, err := format.Source(buf.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile("zones_gen.go", src, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("zones_gen.go: %d zones, tz database %s\n", len(names), version)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "genzones:", err)
	os.Exit(1)
}
