// Starting points. Each one is chosen to show something specific; the notes
// describe what robfig/cron does, and the engine recomputes it live.
export const PRESETS = [
  {
    id: 'sydney-backup',
    name: 'Nightly backup at 02:30, Sydney',
    note: 'skipped in October, runs twice in April',
    expr: '30 2 * * *',
    zones: ['Australia/Sydney', 'Europe/London', 'America/New_York'],
    mode: 'shared',
  },
  {
    id: 'standup',
    name: 'Weekday stand-up, New York',
    note: 'read in London and Kolkata',
    expr: '0 9 * * 1-5',
    zones: ['America/New_York', 'Europe/London', 'Asia/Kolkata'],
    mode: 'shared',
  },
  {
    id: 'ny-0230',
    name: '02:30 nightly, New York',
    note: 'skipped in March; 02:30 happens only once in November',
    expr: '30 2 * * *',
    zones: ['America/New_York'],
    mode: 'shared',
  },
  {
    id: 'london-0130',
    name: '01:30 nightly, London',
    note: 'skipped in March, twice in October',
    expr: '30 1 * * *',
    zones: ['Europe/London'],
    mode: 'shared',
  },
  {
    id: 'each-0130',
    name: '01:30 on three servers, each on local time',
    note: 'the clock changes land on different dates',
    expr: '30 1 * * *',
    zones: ['America/New_York', 'Europe/London', 'Australia/Sydney'],
    mode: 'each',
  },
  {
    id: 'utc-15',
    name: 'Every 15 minutes on a UTC server',
    note: 'read in Los Angeles',
    expr: '*/15 * * * *',
    zones: ['UTC', 'America/Los_Angeles'],
    mode: 'shared',
  },
  {
    id: 'lord-howe',
    name: 'Half-hour clock change, Lord Howe Island',
    note: '02:15 falls in a 30-minute gap',
    expr: '15 2 * * *',
    zones: ['Australia/Lord_Howe'],
    mode: 'shared',
  },
  {
    id: 'havana',
    name: 'Midnight job where clocks change at midnight, Havana',
    note: '00:00 missing one day, twice another',
    expr: '0 0 * * *',
    zones: ['America/Havana'],
    mode: 'shared',
  },
  {
    id: 'leap-day',
    name: 'Leap day, 29 February',
    note: 'from January 2028',
    expr: '0 12 29 2 *',
    zones: ['UTC'],
    mode: 'shared',
    from: '2028-01',
  },
  {
    id: 'either-day',
    name: 'The either-day rule: the 1st or a Monday',
    note: 'both day fields set, so cron matches either',
    expr: '0 6 1 * 1',
    zones: ['Europe/London'],
    mode: 'shared',
  },
  {
    id: 'every-minute',
    name: 'Every minute',
    note: 'the heaviest case: 525,600 firings a year',
    expr: '* * * * *',
    zones: ['Europe/Berlin'],
    mode: 'shared',
  },
];
